import:
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-base-r4.0.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-vms-r4.0.yml

language: python
python: 3.7
install:
 - pip install -r ci/requirements.txt
jobs:
  include:
   - script: 
      - python -m unittest discover -v imgconverter -p test.py
     python: 2.7
   - script: 
      - python -m unittest discover -v imgconverter -p test.py
     python: 3.5
   - script:
      - python -m unittest discover -v imgconverter -p test.py
     python: 3.6
   - script: 
      - python -m unittest discover -v imgconverter -p test.py
     python: 3.7
   - stage: deploy
     python: 3.5
     env: DIST_DOM0=fc25
     script: ~/qubes-builder/scripts/travis-deploy

